fuchuang:
  datasource:
    driver-class-name: org.postgresql.Driver
    host: pgm-bp1m35r42v5tn93aso.pg.rds.aliyuncs.com
    port: 5432
    database: ai_career_plan
    username: ai_career_plan
    password: Syy666666@
    schema: ai_career_plan
  alioss:
    endpoint: ${FUCHUANG_ALIOSS_ENDPOINT}
    bucket-name: ${FUCHUANG_ALIOSS_BUCKET_NAME}
  redis:
    port: ${FUCHUANG_REDIS_PORT}
    host: ${FUCHUANG_REDIS_HOST}
    database: ${FUCHUANG_REDIS_DATABASE}
spring:
  data:
    redis:
      client-type: lettuce
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 30000ms
      connect-timeout: 30000ms
      read-timeout: 30000ms