Spring:
    application:
      name: fuchuang
    ai:
      openai:
        base-url: https://dashscope.aliyuncs.com/compatible-mode
        api-key: ${OPENAI_API_KEY}
        chat:
          options:
            model: qwen-max-latest
logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
    com.itsheng.service: debug
fuchuang:
  jwt:
    # ??jwt??????????
    secret: itsheng
    # ??jwt????
    ttl: 72000000000000000
    # ?????????????
    tokenName: token
