server:
  port: 8081

spring:
  data:
    redis:
      port: ${fuchuang.redis.port}
      host: ${fuchuang.redis.host}
      database: ${fuchuang.redis.database}
      timeout: 5000
  profiles:
    active: dev
  application:
    name: fuchuang
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  datasource:
    driver-class-name: ${fuchuang.datasource.driver-class-name}
    url: jdbc:postgresql://${fuchuang.datasource.host}:${fuchuang.datasource.port}/${fuchuang.datasource.database}?currentSchema=${fuchuang.datasource.schema}
    username: ${fuchuang.datasource.username}
    password: ${fuchuang.datasource.password}
  ai:
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: qwen3-max
#     嵌入模型配置
      embedding:
        options:
          model: text-embedding-v4
          dimensions: 1024
#   pgvector配置
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1024

mybatis:
  # mapper 配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.itsheng.pojo.entity
  configuration:
    # 开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
    com.itsheng.service: debug

fuchuang:
  jwt:
    # jwt 签名密钥（至少32字符，满足HS256的256bits要求）
    secret: itsheng2024fuchuangaiuniversitysecretkey
    # jwt 过期时间
    ttl: 72000000000000000
    # 令牌名称
    tokenName: token
  alioss:
    endpoint: ${fuchuang.alioss.access-key-secret}
    access-key-id: ${fuchuang.alioss.access-key-id}
    access-key-secret: ${fuchuang.alioss.access-key-secret}
    bucket-name: ${fuchuang.alioss.bucket-name}