/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#57657a",
        "on-surface": "#191c1e",
        "surface-container-highest": "#e0e3e5",
        "secondary-container": "#d5e3fc",
        "on-secondary-fixed-variant": "#3a485b",
        "surface": "#f7f9fb",
        "surface-container-low": "#f2f4f6",
        "primary-container": "#0056d2",
        "on-primary-container": "#ccd8ff",
        "primary": "#0040a1",
        "inverse-surface": "#2d3133",
        "surface-container-high": "#e6e8ea",
        "surface-variant": "#e0e3e5",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#b2c5ff",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "surface-dim": "#d8dadc",
        "tertiary-fixed-dim": "#4cd6ff",
        "on-tertiary-container": "#98e3ff",
        "surface-tint": "#0056d2",
        "on-primary-fixed": "#001847",
        "tertiary-container": "#00677f",
        "on-error-container": "#93000a",
        "background": "#f7f9fb",
        "inverse-on-surface": "#eff1f3",
        "error": "#ba1a1a",
        "primary-fixed": "#dae2ff",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#b9c7df",
        "secondary": "#515f74",
        "outline-variant": "#c3c6d6",
        "on-secondary-fixed": "#0d1c2e",
        "tertiary-fixed": "#b7eaff",
        "on-tertiary-fixed-variant": "#004e60",
        "on-background": "#191c1e",
        "tertiary": "#004d60",
        "inverse-primary": "#b2c5ff",
        "on-tertiary-fixed": "#001f28",
        "outline": "#737785",
        "surface-bright": "#f7f9fb",
        "surface-container": "#eceef0",
        "error-container": "#ffdad6",
        "secondary-fixed": "#d5e3fc",
        "on-primary-fixed-variant": "#0040a1",
        "on-surface-variant": "#424654"
      },
      fontFamily: {
        "headline": ["Manrope", "Noto Sans SC", "sans-serif"],
        "body": ["Inter", "Noto Sans SC", "sans-serif"],
        "label": ["Inter", "Noto Sans SC", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
